export const FETCH_SELECTEDITEM_REQUEST = 'FETCH_SELECTEDITEM_REQUEST';
export const FETCH_SELECTEDITEM_SUCCESS = 'FETCH_SELECTEDITEM_SUCCESS';
export const FETCH_SELECTEDITEM_FAILURE = 'FETCH_SELECTEDITEM_FAILURE';
export const REMOVE_SELECTED_ITEM = 'REMOVE_SELECTED_ITEM';
